"""Simple module-level counters for telemetry.

These counters are shared across all async tasks in the same process.
They will be replaced by a proper Prometheus/metrics system in T9.
"""

# ---------------------------------------------------------------------------
# Ingestion daemon counters
# ---------------------------------------------------------------------------

blocks_ingested_total: int = 0
"""Number of mini-blocks ingested and pushed to the Redis stream."""

ws_reconnects_total: int = 0
"""Number of times the WebSocket connection has been re-established."""

ws_keepalive_sent_total: int = 0
"""Number of keepalive eth_chainId requests sent."""

ws_keepalive_errors_total: int = 0
"""Number of keepalive attempts that failed."""

ws_subscription_errors_total: int = 0
"""Number of malformed or non-subscription messages encountered."""

# ---------------------------------------------------------------------------
# Stream processor counters (placeholders, populated by T8)
# ---------------------------------------------------------------------------

stream_reads_total: int = 0
stream_read_errors_total: int = 0

# ---------------------------------------------------------------------------
# State tracker counters (populated by T7)
# ---------------------------------------------------------------------------

blocks_processed_total: int = 0
"""Number of mini-blocks successfully upserted into PostgreSQL."""

blocks_failed_total: int = 0
"""Number of mini-blocks that failed during state tracking."""

# ---------------------------------------------------------------------------
# Embedding / vector counters
# ---------------------------------------------------------------------------

vectors_upserted_total: int = 0
"""Number of vectors successfully upserted to Qdrant."""

vectors_search_total: int = 0
"""Number of similarity searches performed against Qdrant."""

embeddings_cached: int = 0
"""Number of embedding cache hits (duplicate summaries)."""

embeddings_computed: int = 0
"""Number of embedding API calls made (actual compute)."""

degraded_events_total: int = 0
"""Number of blocks processed in degraded mode (embedding unavailable)."""


# ---------------------------------------------------------------------------
# Phase 2: Dispatcher / Execution counters
# ---------------------------------------------------------------------------

dispatcher_intents_received_total: int = 0
"""Number of execution intents received by the worker pool."""

dispatcher_intents_executed_total: int = 0
"""Number of intents successfully executed (tx broadcasted)."""

dispatcher_intents_failed_total: int = 0
"""Number of intents that failed during execution."""

dispatcher_intents_rejected_total: int = 0
"""Number of intents rejected (slippage cap, invalid payload, etc.)."""

# ---------------------------------------------------------------------------
# Phase 2: Balance tracking counters
# ---------------------------------------------------------------------------

transfer_events_parsed_total: int = 0
"""Number of Transfer events successfully parsed from mini-block receipts."""

transfer_events_failed_total: int = 0
"""Number of Transfer events that failed to parse."""

transfer_events_skipped_total: int = 0
"""Number of logs skipped (non-Transfer topic, malformed, etc.)."""

asset_balances_upserted_total: int = 0
"""Number of AssetBalance rows upserted."""

asset_balances_queried_total: int = 0
"""Number of AssetBalance queries performed."""

execution_queue_depth: int = 0
"""Approximate depth of the execution stream (set by worker pool)."""

# ---------------------------------------------------------------------------
# Phase 3: LangGraph Agent counters
# ---------------------------------------------------------------------------

agent_invocations_total: int = 0
"""Number of agent graph invocations."""

agent_invocations_success_total: int = 0
"""Number of agent invocations that completed without error."""

agent_invocations_error_total: int = 0
"""Number of agent invocations that ended with an error."""

agent_payloads_generated_total: int = 0
"""Number of execution payloads generated by the agent."""

agent_tool_call_total: int = 0
"""Total number of tool calls made by the agent."""

agent_loop_duration_seconds: float = 0.0
"""Duration of the last agent poll loop iteration."""

trigger_price_evaluated_total: int = 0
"""Number of price-threshold trigger evaluations."""

trigger_time_evaluated_total: int = 0
"""Number of time-bound trigger evaluations."""


__all__ = [
    "blocks_ingested_total",
    "ws_reconnects_total",
    "ws_keepalive_sent_total",
    "ws_keepalive_errors_total",
    "ws_subscription_errors_total",
    "stream_reads_total",
    "stream_read_errors_total",
    "blocks_processed_total",
    "blocks_failed_total",
    "vectors_upserted_total",
    "vectors_search_total",
    "embeddings_cached",
    "embeddings_computed",
    "degraded_events_total",
    "dispatcher_intents_received_total",
    "dispatcher_intents_executed_total",
    "dispatcher_intents_failed_total",
    "dispatcher_intents_rejected_total",
    "transfer_events_parsed_total",
    "transfer_events_failed_total",
    "transfer_events_skipped_total",
    "asset_balances_upserted_total",
    "asset_balances_queried_total",
    "execution_queue_depth",
    "agent_invocations_total",
    "agent_invocations_success_total",
    "agent_invocations_error_total",
    "agent_payloads_generated_total",
    "agent_tool_call_total",
    "agent_loop_duration_seconds",
    "trigger_price_evaluated_total",
    "trigger_time_evaluated_total",
]
